language: python

python:
  - "3.6"

install:
  - "pip3 install -r requirements.txt"

script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"
  - "python manage.py test test.unit_tests"