# spatialdatahub.org/.travis.yml

sudo: required

language:
  - python

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"

script:
  - "echo 'hey!'"
  - "python manage.py test test.unit_tests --settings=main.settings.dev"

before_deploy: "echo 'ready to deploy'"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-central-1"  
  app: "spatialdatahub"
  env: "spatialdatahub-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-707675293479"
  on:
    branch: master
